backend:
  name: github
  repo: masjidnoorislam-byte/adamasjid.com
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://masjidnoorislam.pages.dev
display_url: https://masjidnoorislam.pages.dev

collections:
  - name: "kegiatan"
    label: "Kegiatan"
    folder: "content/kegiatan"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "judul", widget: "string" }
      - { label: "Tanggal", name: "tanggal", widget: "datetime" }
      - { label: "Isi", name: "body", widget: "markdown" }
